name: Build php8.2 Apache

on:
  schedule:
  - cron: "0 8 * * 6"
  workflow_dispatch:


jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
     
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./php8.2-apache
          file: ./php8.2-apache/Dockerfile
          tags: notglossy/wordpress:php8.2-apache
